### PR TITLE
2 Fixes

### PR DESCRIPTION
**Pull request by cloakedninjas**
If you're interested, here's 2 commits to fix:

#26 and #23

### CODE REVIEW

**Comment by paulfalgout** [comment]
Not delegating the focus/blur events just means that re-rendering the view will leave orphaned listeners and the newly rendered view won't have the events.  This should have used the `useCapture` flag for these events

**Comment by akre54** [comment]
@paulfalgout got a fix?

**Comment by paulfalgout** [comment]
@akre54 playing with it now.  Just realized the issue

**Comment by akre54** [comment]
Want to open a pull?

**Comment by paulfalgout** [comment]
😃 . Yeah I put it on my list.  I'm not in a hurry though.

**Comment by akre54** [comment]
Okay, happy to take a look whenever you have something ready

**Pull request merged**
